import { Forum } from "next/font/google";
import "./globals.css";
import ClientLayout from "./clientLayout";

const forum = Forum({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: "Auto service App",
  description: "Generated by create next app",
  icons: { icon: "/logo_black.png" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={forum.className}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
